import { DhikrDetail } from './dhikr-data'

export const POST_SALAH_DHIKR_DETAIL: DhikrDetail = {
  title: 'Post-Salah Dhikr',
  description: 'Authentic remembrances after the obligatory prayer',
  sequence: [
    {
      id: 'sequence-istighfar',
      title: 'Seek forgiveness',
      description: 'Say Astaghfirullah three times immediately after salam.',
      tag: '3x',
    },
    {
      id: 'sequence-salam',
      title: 'Allahumma antas-salam',
      description: 'Then say the remembrance taught after completing salah.',
      tag: '1x',
    },
    {
      id: 'sequence-tasbih',
      title: 'Tasbih set',
      description: 'Say SubhanAllah, Alhamdulillah, and Allahu Akbar.',
      tag: '33 / 33 / 33',
    },
    {
      id: 'sequence-complete-hundred',
      title: 'Complete the hundred',
      description: 'Finish with the tahlil narrated in Sahih Muslim.',
      tag: '1x',
    },
    {
      id: 'sequence-ayat-kursi',
      title: 'Ayat al-Kursi',
      description: 'Recite Surah al-Baqarah 2:255 after the obligatory prayer.',
      tag: '1x',
    },
    {
      id: 'sequence-muawwidhat',
      title: 'The three Quls',
      description: 'Recite al-Ikhlas, al-Falaq, and an-Nas after every prayer.',
      tag: '1x each',
    },
  ],
  tasbihGroupIndex: 2,
  tasbihGroup: [
    {
      id: 'post-salah-subhanallah',
      arabic: 'سُبْحَانَ اللهِ',
      transliteration: 'SubhanAllah',
      translation: 'Allah is free from imperfection.',
      targetCount: 33,
      accent: '#C8A951',
    },
    {
      id: 'post-salah-alhamdulillah',
      arabic: 'الحَمْدُ للهِ',
      transliteration: 'Alhamdulillah',
      translation: 'All praise belongs to Allah.',
      targetCount: 33,
      accent: '#C8A951',
    },
    {
      id: 'post-salah-allahu-akbar',
      arabic: 'اللهُ أَكْبَرُ',
      transliteration: 'Allahu Akbar',
      translation: 'Allah is the Greatest.',
      targetCount: 33,
      accent: '#C8A951',
    },
  ],
  items: [
    {
      id: 'post-salah-istighfar',
      arabic: 'أَسْتَغْفِرُ اللهَ',
      transliteration: 'Astaghfirullah',
      translation: "I seek Allah's forgiveness.",
      targetCount: 3,
      accent: '#C8A951',
    },
    {
      id: 'post-salah-antas-salam',
      arabic: 'اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الجَلَالِ وَالإِكْرَامِ',
      transliteration: "Allahumma antas-salam, wa minkas-salam, tabarakta ya dhal-jalali wal-ikram",
      translation: 'O Allah, You are Peace and from You comes peace. Blessed are You, Owner of majesty and honor.',
      targetCount: 1,
      accent: '#C8A951',
    },
    {
      id: 'post-salah-complete-hundred',
      arabic: 'لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ المُلْكُ وَلَهُ الحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
      transliteration: "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamd, wa huwa 'ala kulli shay'in qadir",
      translation: 'None has the right to be worshipped except Allah alone with no partner. His is the dominion and praise, and He is able to do all things.',
      targetCount: 1,
      accent: '#C8A951',
    },
    {
      id: 'post-salah-ayat-kursi',
      arabic: 'اللَّهُ لَا إِلَهَ إِلَّا هُوَ الحَيُّ القَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ العَلِيُّ العَظِيمُ',
      transliteration: 'Ayat al-Kursi',
      translation: 'Allah, there is no deity except Him, the Ever-Living, the Sustainer of all existence. Surah al-Baqarah 2:255.',
      targetCount: 1,
      accent: '#4F6F52',
    },
    {
      id: 'post-salah-ikhlas',
      arabic: 'قُلْ هُوَ اللهُ أَحَدٌ ۝ اللهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ',
      transliteration: 'Qul huwa Allahu ahad',
      translation: 'Say: He is Allah, One. Surah al-Ikhlas.',
      targetCount: 1,
      accent: '#4F6F52',
    },
    {
      id: 'post-salah-falaq',
      arabic: 'قُلْ أَعُوذُ بِرَبِّ الفَلَقِ ۝ مِنْ شَرِّ مَا خَلَقَ ۝ وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ ۝ وَمِنْ شَرِّ النَّفَّاثَاتِ فِي العُقَدِ ۝ وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ',
      transliteration: "Qul a'udhu birabbil-falaq",
      translation: 'Say: I seek refuge in the Lord of daybreak. Surah al-Falaq.',
      targetCount: 1,
      accent: '#4F6F52',
    },
    {
      id: 'post-salah-nas',
      arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ ۝ مَلِكِ النَّاسِ ۝ إِلَهِ النَّاسِ ۝ مِنْ شَرِّ الوَسْوَاسِ الخَنَّاسِ ۝ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ۝ مِنَ الجِنَّةِ وَالنَّاسِ',
      transliteration: "Qul a'udhu birabbin-nas",
      translation: 'Say: I seek refuge in the Lord of mankind. Surah an-Nas.',
      targetCount: 1,
      accent: '#4F6F52',
    },
  ],
}
